import { useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { ProductListItem } from '@/src/components/ProductListItem';
import { useProducts } from '@/src/hooks/useProducts';

export default function ProductsScreen() {
  const { products, lastSync, isLoadingLocal, isSyncing, error, usingOfflineData, sync } = useProducts(); const [message, setMessage] = useState<string | null>(null);
  const refresh = async () => { const ok = await sync(); setMessage(ok ? 'Produtos atualizados e salvos no aparelho.' : 'API indisponível. Os dados locais foram mantidos.'); if (ok) Alert.alert('Sincronização concluída', 'Os produtos estão disponíveis offline.'); };
  return <SafeAreaView style={styles.safe}><View style={styles.header}><View><Text style={styles.title}>Produtos</Text><Text style={styles.subtitle}>{products.length} cadastrados</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Atualizar produtos" disabled={isSyncing} onPress={refresh} style={styles.button}>{isSyncing ? <ActivityIndicator color="#fff" /> : <Text style={styles.refresh}>↻</Text>}</Pressable></View>
    <View style={styles.meta}><Text style={styles.sync}>Última atualização: {lastSync ? new Date(lastSync).toLocaleString('pt-BR') : 'nunca'}</Text>{(usingOfflineData || error) && <Text style={styles.warning}>Modo offline — dados locais em uso.</Text>}{message && <Text style={styles.message}>{message}</Text>}</View>
    <FlatList data={products} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} refreshing={isSyncing} onRefresh={refresh} renderItem={({ item }) => <ProductListItem product={item} />} ItemSeparatorComponent={() => <View style={{ height: 10 }} />} ListEmptyComponent={<Text style={styles.empty}>{isLoadingLocal ? 'Carregando produtos locais…' : 'Nenhum produto salvo. Toque em ↻ para sincronizar.'}</Text>} />
  </SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#f8fafc' }, header: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 14, backgroundColor: '#0f172a', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { color: '#fff', fontSize: 28, fontWeight: '800' }, subtitle: { color: '#94a3b8', marginTop: 2 }, button: { width: 44, height: 44, borderRadius: 14, backgroundColor: '#2563eb', alignItems: 'center', justifyContent: 'center' }, refresh: { color: '#fff', fontSize: 28, lineHeight: 30 }, meta: { padding: 16, gap: 4 }, sync: { color: '#64748b', fontSize: 12 }, warning: { color: '#b45309', fontWeight: '600' }, message: { color: '#334155' }, list: { padding: 16, paddingTop: 0, flexGrow: 1 }, empty: { color: '#64748b', textAlign: 'center', marginTop: 60, paddingHorizontal: 30 } });
